### ISSUE TITLE
Online media plugin takes a long time to show yt-dlp version

### ISSUE THREAD

**Issue by low-batt** [iina/plugin-online-media#3]
### IINA Version

1.4.0-beta1 Build 150 (internal test build)

### Release Channel

Other

### macOS Version

macOS 15.3

### Steps to Reproduce

- Make sure [yt-dlp](https://github.com/yt-dlp/yt-dlp) is not installed so IINA must use the embedded version
- Install and activate the [Online Media](https://github.com/iina/plugin-online-media) plugin
- Start IINA
- Click on `Manage yt-dlp and Downloads…` under the `Plugin` menu
- The `Downloads -- Online Media` window appears
- The `Status` section shows the text `Checking for yt-dlp binary…` and a `Download latest yt-dlp` button
- And nothing happens
- No version is shown
- No throbber
- It just sits there
- For a long time

### Expected Behavior

When the [Online Media](https://github.com/iina/plugin-online-media) plugin is doing something that takes more than a second or two it provides some sort of indication that work is in progress.

### Actual Behavior

The [Online Media](https://github.com/iina/plugin-online-media) plugin takes more than 15 seconds to show the [yt-dlp](https://github.com/yt-dlp/yt-dlp) version. While it is working there is no indication that it is busy obtaining the version.

For the download operation it displays a simple throbber. Unfortunately it looks like that is also needed while getting the `yt-dlp` version. The delay is not in the plugin. Executing the `yt-dlp` embedded in IINA takes 18 seconds in this experiment:
```text
low-batt@urp ~$ time ~/Documents/builds/iina-official/releases/IINA.app/Contents/MacOS/youtube-dl --version
2025.01.12

real	0m18.631s
user	0m0.638s
sys	0m0.355s
low-batt@urp ~$ 
```

The reason why it is taking so long is explained in [this comment](https://github.com/yt-dlp/yt-dlp/issues/10425#issuecomment-2227034674):
> `yt-dlp_macos` is a pyinstaller-bundled "onefile" executable, which means every time you execute it, it first needs to unpack its contents (~30-50MB of shared libraries and script files) into a temporary directory before yt-dlp itself is executed. These temp files are cleaned up once the executable has finished, so the security scanning would be invoked on every run, not just the first run.
>
> An alternative would be the `yt-dlp_macos.zip` "onedir" build, where you unpack it yourself into a directory upon installation and no further unpacking is ever needed. The downside with the onedir build is that you can't use the yt-dlp self-updater (`-U/--update-to`); you would need to manually download updates from Github.

IINA does not make use of the built in `yt-dlp` self-updater. From a quick look at the [Online Media](https://github.com/iina/plugin-online-media) plugin sources I don't think it does either. So that restriction does not preclude either from using `yt-dlp_macos.zip`.

The problem will be in satisfying the code signing requirements. Expanding the `.zip` file creates lots of files that need to be signed. Should not be a problem for the IINA build. Not sure how the plugin would handle this.

As the plugin supports using a `yt-dlp` supplied by the user, it can't assume obtaining the version is going to be quick and needs to be prepared to show a throbber.

And of course this performance issue goes beyond obtaining the `yt-dlp` version. This causes a long delay when opening a stream. If possible it is highly desirable to solve this startup performance problem.

### How often can you reproduce the issue

Every time.

### Required Actions

- [x] I tried my best to search from the existing issues (including closed issues) and didn't find duplicated issues.

### Optional Actions

- [x] I tested with the Nightly build and confirmed the issue is not fixed.
- [ ] I tested with the latest version of mpv and confirmed mpv doesn't have this issue.

**Comment by low-batt** [comment]
I'm seeing incorrect behavior testing IINA 1.4.0-beta1 with Online Media 0.96.0 trying to update yt-dlp.

I forgot that I had set `Use custom youtube-dl/yt-dl` to use the brew installed yt-dlp. Should we even be mentioning `youtube-dl` these days? Have we tested to see if `youtube-dl` still works with IINA?

Anyway, the `Download latest yt-dlp` button was still enabled even though the brew installed yt-dlp was being used. Shouldn't that button be disabled if the plugin managed yt-dlp is not being used?

I went ahead and clicked on the button to update yt-dlp. This is what the window looked like after the download finished.
![Image](https://github.com/user-attachments/assets/96c57b91-eee3-4a76-a854-c01f4e837ea4)

This is what that looked like in the IINA log. Notice the script **error** at the end.
```text
13:12:05.497 [global - Online Media][d] Found youtube-dl; using /opt/homebrew/bin/yt-dlp
13:12:05.497 [global - Online Media][d] Executing /opt/homebrew/bin/yt-dlp --get-filename https://www.youtube.com/watch?v=IxX_QHay02M
13:12:05.501 [video0][v] Display link stopped
13:12:08.742 [global - Online Media][d] W&W - OIIA OIIA (Spinning Cat) [IxX_QHay02M].mp4
13:12:08.742 [global - Online Media][d] Executing /opt/homebrew/bin/yt-dlp -P ~/Downloads --progress-template !!%(progress.downloaded_bytes)s-%(progress.total_bytes)s-%(progress.eta)s -- https://www.youtube.com/watch?v=IxX_QHay02M
13:12:13.094 [global - Online Media][d] Download finished
13:15:05.778 [global - Online Media][d] Downloading yt-dlp to /Users/low-batt/Library/Application Support/com.colliderli.iina/plugins/.data/io.iina.ytdl/yt-dlp_1746983705775.zip
13:15:12.438 [global - Online Media][d] Executing /bin/bash -c 
      unzip '/Users/low-batt/Library/Application Support/com.colliderli.iina/plugins/.data/io.iina.ytdl/yt-dlp_1746983705775.zip' -d '/Users/low-batt/Library/Application Support/com.colliderli.iina/plugins/.data/io.iina.ytdl/yt-dlp_1746983705775' &&
      mv '/Users/low-batt/Library/Application Support/com.colliderli.iina/plugins/.data/io.iina.ytdl/yt-dlp_1746983705775' '/Users/low-batt/Library/Application Support/com.colliderli.iina/plugins/.data/io.iina.ytdl/yt-dlp' &&
      rm '/Users/low-batt/Library/Application Support/com.colliderli.iina/plugins/.data/io.iina.ytdl/yt-dlp_1746983705775.zip' &&
      xattr -cr '/Users/low-batt/Library/Application Support/com.colliderli.iina/plugins/.data/io.iina.ytdl/yt-dlp'
      
13:15:13.406 [global - Online Media][d] Found youtube-dl; using /opt/homebrew/bin/yt-dlp
13:15:13.407 [global - Online Media][d] Binary path: /opt/homebrew/bin/yt-dlp
13:15:13.407 [global - Online Media][d] Executing /opt/homebrew/bin/yt-dlp --version
13:15:13.980 [global - Online Media][d] Version: 2025.03.31

13:15:54.319 [global - Online Media][d] Found youtube-dl; using /opt/homebrew/bin/yt-dlp
13:15:54.319 [global - Online Media][d] Binary path: /opt/homebrew/bin/yt-dlp
13:15:54.320 [global - Online Media][d] Executing /opt/homebrew/bin/yt-dlp --version
13:15:54.897 [global - Online Media][d] Version: 2025.03.31

13:16:14.510 [global - Online Media][d] Downloading yt-dlp to /Users/low-batt/Library/Application Support/com.colliderli.iina/plugins/.data/io.iina.ytdl/yt-dlp_1746983774509.zip
13:16:16.060 [global - Online Media][d] Executing /bin/bash -c 
      unzip '/Users/low-batt/Library/Application Support/com.colliderli.iina/plugins/.data/io.iina.ytdl/yt-dlp_1746983774509.zip' -d '/Users/low-batt/Library/Application Support/com.colliderli.iina/plugins/.data/io.iina.ytdl/yt-dlp_1746983774509' &&
      mv '/Users/low-batt/Library/Application Support/com.colliderli.iina/plugins/.data/io.iina.ytdl/yt-dlp_1746983774509' '/Users/low-batt/Library/Application Support/com.colliderli.iina/plugins/.data/io.iina.ytdl/yt-dlp' &&
      rm '/Users/low-batt/Library/Application Support/com.colliderli.iina/plugins/.data/io.iina.ytdl/yt-dlp_1746983774509.zip' &&
      xattr -cr '/Users/low-batt/Library/Application Support/com.colliderli.iina/plugins/.data/io.iina.ytdl/yt-dlp'
      
13:16:17.021 [global - Online Media][d] Found youtube-dl; using /opt/homebrew/bin/yt-dlp
13:16:17.021 [global - Online Media][d] Binary path: /opt/homebrew/bin/yt-dlp
13:16:17.022 [global - Online Media][d] Executing /opt/homebrew/bin/yt-dlp --version
13:16:17.599 [global - Online Media][d] Version: 2025.03.31

13:16:33.201 [iina][d] JS:Online Media Preference page Script error. 0,0: <null>
```

I made sure to clear the `Use custom youtube-dl/yt-dl` setting and restart IINA. After restart clicking the `Verify yt-dlp binary` took a long time and indicated the yt-dlp _bundled with IINA_ was being used.
![Image](https://github.com/user-attachments/assets/48669f1d-29ec-4522-a875-63b5c7bc9244)

Restarting IINA and trying the update again still shows bundled yt-dlp is being used.
![Image](https://github.com/user-attachments/assets/c66f5db9-c7c2-4b79-a1f3-fe989ff39c3a)

This is what that looked like in the IINA log:
```text
13:46:42.936 [global - Online Media][d] Downloading yt-dlp to /Users/low-batt/Library/Application Support/com.colliderli.iina/plugins/.data/io.iina.ytdl/yt-dlp_1746985602935.zip
13:46:48.870 [global - Online Media][d] Executing /bin/bash -c 
      unzip '/Users/low-batt/Library/Application Support/com.colliderli.iina/plugins/.data/io.iina.ytdl/yt-dlp_1746985602935.zip' -d '/Users/low-batt/Library/Application Support/com.colliderli.iina/plugins/.data/io.iina.ytdl/yt-dlp_1746985602935' &&
      mv '/Users/low-batt/Library/Application Support/com.colliderli.iina/plugins/.data/io.iina.ytdl/yt-dlp_1746985602935' '/Users/low-batt/Library/Application Support/com.colliderli.iina/plugins/.data/io.iina.ytdl/yt-dlp' &&
      rm '/Users/low-batt/Library/Application Support/com.colliderli.iina/plugins/.data/io.iina.ytdl/yt-dlp_1746985602935.zip' &&
      xattr -cr '/Users/low-batt/Library/Application Support/com.colliderli.iina/plugins/.data/io.iina.ytdl/yt-dlp'
      
13:46:49.784 [global - Online Media][d] Found youtube-dl; using youtube-dl
13:46:49.784 [global - Online Media][d] Binary path: youtube-dl
13:46:49.784 [global - Online Media][d] Executing /Applications/IINA.app/Contents/MacOS/youtube-dl --version
13:47:02.823 [global - Online Media][d] Version: 2025.01.12
```

**Comment by lhc70000** [comment]
Should be fixed in 0.9.6.

**Comment by low-batt** [comment]
I'm using version 0.9.6 and it is not working for me. The problems I describe [above](https://github.com/iina/plugin-online-media/issues/3#issuecomment-2870029846) happened testing 1.4.0-beta1 + 0.9.6.

This shows what is going wrong:
```text
mv: rename /Users/low-batt/Library/Application Support/com.colliderli.iina/plugins/.data/io.iina.ytdl/yt-dlp_1746985602935 to /Users/low-batt/Library/Application Support/com.colliderli.iina/plugins/.data/io.iina.ytdl/yt-dlp: Not a directory
```

Checking the plugins data directory shows I still have a yt-dlp binary file downloaded by previous versions of the plugin that is causing the mv command to fail:
```
low-batt@gag io.iina.ytdl$ ls -la
total 651048
drwxr-xr-x  13 low-batt  staff       416 May 11 13:46 .
drwxr-xr-x   4 low-batt  staff       128 Jan 17 10:53 ..
-rw-r--r--   1 low-batt  staff  34388704 Nov  3  2024 yt-dlp
drwxr-xr-x@  4 low-batt  staff       128 May 11 13:15 yt-dlp_1746983705775
-rw-r--r--@  1 low-batt  staff  59787589 May 11 13:15 yt-dlp_1746983705775.zip
drwxr-xr-x@  4 low-batt  staff       128 May 11 13:16 yt-dlp_1746983774509
-rw-r--r--@  1 low-batt  staff  59787589 May 11 13:16 yt-dlp_1746983774509.zip
drwxr-xr-x@  4 low-batt  staff       128 May 11 13:18 yt-dlp_1746983914039
-rw-r--r--@  1 low-batt  staff  59787589 May 11 13:18 yt-dlp_1746983914039.zip
drwxr-xr-x@  4 low-batt  staff       128 May 11 13:43 yt-dlp_1746985429035
-rw-r--r--@  1 low-batt  staff  59787589 May 11 13:43 yt-dlp_1746985429035.zip
drwxr-xr-x@  4 low-batt  staff       128 May 11 13:46 yt-dlp_1746985602935
-rw-r--r--@  1 low-batt  staff  59787589 May 11 13:46 yt-dlp_1746985602935.zip
low-batt@gag io.iina.ytdl$
```

I deleted the yt-dlp binary file from the directory and things started working. But users who had the old version of the plugin download yt-dlp will also run into this problem.

**Comment by lhc70000** [comment]
0.9.7 should have fixed this.
